token: your_huggingface_token # replace with your Hugging Face API token 
model: 02loveslollipop/furina_ai_mistral_7b # replace with your model name or path
device: cpu # replace with 'cuda' if you are using CUDA compatible GPU, otherwise 'cpu'